// import {fetchFromApi} from "@/lib/api/fetchFromApi";
import {Reservation} from "@/types/reservation";

export async function getPastReservations(): Promise<Reservation[]> {
    // return await fetchFromApi("/reservations/past", {
    //     method: "GET"
    // });

    return [
        {
            id: "res_001",
            guestName: "John Doe",
            guestEmail: "john@example.com",
            guestPhone: "+1 234-567-8900",
            apartmentName: "Lakeview Apartment",
            checkIn: "2025-08-01T14:00:00Z",
            checkOut: "2025-08-05T10:00:00Z",
            nights: 4,
            totalPrice: 420,
            pricePerNight: 105,
            paymentStatus: "paid",
            bookingStatus: "confirmed",
            createdAt: "2025-07-10T12:00:00Z",
            numberOfGuests: 2,
            bookingChannel: "website",
            notes: "Requested early check-in.",
        },
        {
            id: "res_002",
            guestName: "Maria Petrova",
            guestEmail: "maria@example.com",
            guestPhone: "+359 887 123-456",
            apartmentName: "Central City Loft",
            checkIn: "2025-07-12T14:00:00Z",
            checkOut: "2025-07-18T10:00:00Z",
            nights: 6,
            totalPrice: 680,
            pricePerNight: 113.33,
            paymentStatus: "paid",
            bookingStatus: "confirmed",
            createdAt: "2025-06-25T09:30:00Z",
            numberOfGuests: 2,
            bookingChannel: "booking.com",
            notes: "Paid via credit card.",
        },
        {
            id: "res_003",
            guestName: "Aleksandar Jovanović",
            guestEmail: "aleksandar@example.com",
            guestPhone: "+381 65 123-4567",
            apartmentName: "Sunset Studio",
            checkIn: "2025-06-20T14:00:00Z",
            checkOut: "2025-06-23T10:00:00Z",
            nights: 3,
            totalPrice: 250,
            pricePerNight: 83.33,
            paymentStatus: "refunded",
            bookingStatus: "cancelled",
            createdAt: "2025-06-10T10:00:00Z",
            numberOfGuests: 1,
            bookingChannel: "airbnb",
            notes: "Cancelled due to travel changes.",
        },
        {
            id: "res_004",
            guestName: "Elena Dimitrova",
            guestEmail: "elena@example.com",
            guestPhone: "+359 889 654-321",
            apartmentName: "Riverside Apartment",
            checkIn: "2025-05-10T14:00:00Z",
            checkOut: "2025-05-15T10:00:00Z",
            nights: 5,
            totalPrice: 560,
            pricePerNight: 112,
            paymentStatus: "pending",
            bookingStatus: "confirmed",
            createdAt: "2025-04-25T08:45:00Z",
            numberOfGuests: 4,
            bookingChannel: "direct",
            notes: "",
            specialRequests: "Late check-in requested",
        },
    ];
}

export async function getFutureReservations(): Promise<Reservation[]> {
    // return await fetchFromApi("/reservations/future", {
    //     method: "GET"
    // });

    return [
        {
            id: "res_101",
            guestName: "Sophie Laurent",
            guestEmail: "sophie@example.com",
            guestPhone: "+33 6 12 34 56 78",
            apartmentName: "Lakeview Apartment",
            checkIn: "2025-10-15T14:00:00Z",
            checkOut: "2025-10-20T10:00:00Z",
            nights: 5,
            totalPrice: 525,
            pricePerNight: 105,
            paymentStatus: "pending",
            bookingStatus: "confirmed",
            createdAt: "2025-10-01T15:30:00Z",
            numberOfGuests: 2,
            bookingChannel: "booking.com",
            notes: "First time guest",
            specialRequests: "High floor preferred",
        },
        {
            id: "res_102",
            guestName: "Marco Rossi",
            guestEmail: "marco@example.com",
            guestPhone: "+39 328 1234567",
            apartmentName: "Central City Loft",
            checkIn: "2025-10-18T14:00:00Z",
            checkOut: "2025-10-25T10:00:00Z",
            nights: 7,
            totalPrice: 791.31,
            pricePerNight: 113.33,
            paymentStatus: "paid",
            bookingStatus: "confirmed",
            createdAt: "2025-09-20T10:15:00Z",
            numberOfGuests: 3,
            bookingChannel: "website",
            notes: "Business trip",
        },
        {
            id: "res_103",
            guestName: "Anna Kowalski",
            guestEmail: "anna@example.com",
            guestPhone: "+48 123 456 7890",
            apartmentName: "Sunset Studio",
            checkIn: "2025-10-22T14:00:00Z",
            checkOut: "2025-10-25T10:00:00Z",
            nights: 3,
            totalPrice: 250,
            pricePerNight: 83.33,
            paymentStatus: "pending",
            bookingStatus: "pending",
            createdAt: "2025-10-10T12:00:00Z",
            numberOfGuests: 1,
            bookingChannel: "airbnb",
            specialRequests: "Early check-in if possible",
        },
        {
            id: "res_104",
            guestName: "David Chen",
            guestEmail: "david@example.com",
            guestPhone: "+1 415-555-0100",
            apartmentName: "Garden View Suite",
            checkIn: "2025-11-01T14:00:00Z",
            checkOut: "2025-11-08T10:00:00Z",
            nights: 7,
            totalPrice: 840,
            pricePerNight: 120,
            paymentStatus: "pending",
            bookingStatus: "confirmed",
            createdAt: "2025-10-05T09:45:00Z",
            numberOfGuests: 2,
            bookingChannel: "direct",
            notes: "Honeymoon trip",
            specialRequests: "Romance package if available",
        },
        {
            id: "res_105",
            guestName: "Lisa Anderson",
            guestEmail: "lisa@example.com",
            guestPhone: "+1 206-555-0147",
            apartmentName: "Mountain View Retreat",
            checkIn: "2025-10-20T14:00:00Z",
            checkOut: "2025-10-23T10:00:00Z",
            nights: 3,
            totalPrice: 360,
            pricePerNight: 120,
            paymentStatus: "paid",
            bookingStatus: "confirmed",
            createdAt: "2025-09-28T14:20:00Z",
            numberOfGuests: 4,
            bookingChannel: "booking.com",
        },
    ]
}